from typing import List

from fastapi import APIRouter

from app.schemas import (
    ProductCreate,
    ProductResponse,
    CouponResponse,
    StatsResponse,
)

# from app.services.admin_service import AdminService

router = APIRouter()

# admin_service = AdminService()


@router.post(
    "/products",
    response_model=ProductResponse,
    status_code=201,
    summary="Create a new product"
)
async def create_product(product: ProductCreate):
    """
    Creates a new product.

    Product ID will be generated by Redis.
    """
    # return await admin_service.create_product(product)

    return ProductResponse(
        id=1,
        name=product.name,
        price=product.price,
        stock=product.stock,
    )


@router.get(
    "/products",
    response_model=List[ProductResponse],
    summary="List all products"
)
async def list_products():
    """
    Returns all products.
    """
    # return await admin_service.list_products()

    return []


@router.post(
    "/generate-discount",
    response_model=CouponResponse,
    summary="Generate a discount coupon"
)
async def generate_discount():
    """
    Generates a discount coupon.

    Note:
    Normally coupons are generated automatically
    after every Nth successful checkout.
    This endpoint is primarily for testing/admin purposes.
    """

    # return await admin_service.generate_discount()

    return CouponResponse(
        code="SAVE10XYZ",
        percentage=10,
        used=False,
    )


@router.get(
    "/coupons",
    response_model=List[CouponResponse],
    summary="List all coupons"
)
async def list_coupons():
    """
    Returns all generated coupons.
    """

    # return await admin_service.list_coupons()

    return []


@router.get(
    "/stats",
    response_model=StatsResponse,
    summary="Store statistics"
)
async def get_stats():
    """
    Returns store analytics.
    """

    # return await admin_service.get_stats()

    return StatsResponse(
        total_orders=0,
        total_items_purchased=0,
        total_revenue=0,
        total_discount_codes=0,
        total_discount_given=0,
    )